<a href="https://colab.research.google.com/github/Saanvi26/Machine-learning/blob/main/Linear_regression_multiple_variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
df=pd.read_csv("Data.csv")
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  650000
2  3200      NaN   18  480000
3  3600      3.0   30  600000
4  4000      5.0   25  530000

In [ ]:
import math
median_bedroom=math.floor(df.bedroom.median())#Replace NaN with median of the bedroom
median_bedroom

3

In [ ]:
df.bedroom=df.bedroom.fillna(median_bedroom)
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  650000
2  3200      3.0   18  480000
3  3600      3.0   30  600000
4  4000      5.0   25  530000

In [13]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedroom','age']],df[['price']]) #(independent,dependent)
reg.predict([[3000,3,40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[664559.76122643]])

In [14]:
reg.intercept_

array([615795.68579568])

In [15]:
reg.coef_

array([[ -100.08140008, 43437.79677113,  5467.37213404]])